POST http://localhost:6000/products
Content-Type: application/json

{
    "nameProduct":"lumpia basah",
    "categories":"cemilan",
    "madeIn":"semarang"
}
###
DELETE http://localhost:6000/products/6756b48cb2510dce90244e94
###

PATCH http://localhost:6000/products/6756b4aeb2510dce90244e96
Content-Type: application/json

{
    "categories":"cemilan",
    "madeIn":"Semarang"
}

###
GET http://localhost:6000/products